version: '3.8'

services:
  php:
    image: php:8.2-cli
    container_name: objectif-php
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    depends_on:
      - database
    entrypoint: >
      /bin/sh -c "apt-get update
      && apt-get install -y unzip git
      && docker-php-ext-install zip
      && curl -sS https://getcomposer.org/installer | php
      && mv composer.phar /usr/local/bin/composer
      && tail -f /dev/null"

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: "!ChangeMe!"
      POSTGRES_USER: app
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  nginx:
    image: nginx:alpine
    container_name: objectif-nginx
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - ./public:/app/public:ro
    depends_on:
      - php

volumes:
  database_data: